#!/usr/bin/env bash
../src/scribbu report -d -t -o report-tdf.tdf ${srcdir}/data
cp -v report-tdf.tdf report-tdf.last.tdf
head -n1 report-tdf.tdf > report-tdf.$$.tdf
tail -n+2 report-tdf.tdf | sort -d >> report-tdf.$$.tdf
# This is irritating, but we need to strip out the paths above
# "data" since we do a dumb diff, below.
sed -e 's_,".*/data",_,"data",_' report-tdf.$$.tdf > report-tdf.tdf
rm report-tdf.$$.tdf
diff report-tdf.tdf ${srcdir}/data/report-tdf-golden.tdf
exit $?
