#!/usr/bin/env bash
export GUILE_AUTO_COMPILE=0
SCRIPT_FILE=/tmp/test-with-track-in.$$
OUTPUT_FILE=/tmp/test-with-track-in.out.$$

cat <<EOF > $SCRIPT_FILE
(use-modules (ice-9 format))
(use-modules (oop goops))
(use-modules (scribbu))

(setlocale LC_ALL "")

(with-track-in
 "${srcdir}/data"
 (lambda (tagset pth v1)
   (unless (or
             (null? v1)
             (member 
                pth 
                (list
                   (format #f "~a/data/Winamp5_normal-128.mp3" (getenv "srcdir")))))
	   (let ((c (slot-ref v1 'comment))
			 (r (make-regexp "rip.*winamp" regexp/icase)))
		 (if (regexp-exec r c)
			 (format #t "~s: ~s\n" pth c))))))
EOF

../src/scribbu -L ${srcdir}/../scheme -s $SCRIPT_FILE > $OUTPUT_FILE
# This is irritating, but we need to strip out the paths above
# "data" since we do a dumb diff, below.
sed -e 's_^".*/data_"data_' $OUTPUT_FILE | sort > with-track-in.log
diff with-track-in.log ${srcdir}/data/with-track-in-golden.log || exit 1
exit 0
