#!/usr/bin/env bash
export GUILE_AUTO_COMPILE=0

eval "$(../src/scribbu -L ${srcdir}/../scheme -s ${srcdir}/test-display.scm ${srcdir} \
        2> >(t_err=$(cat); typeset -p t_err) \
         > >(t_std=$(cat); typeset -p t_std) )"
t_stat=$?
# echo "$t_std"
t_err=$(echo "$t_err" | grep -vE ';;; note: source file .*test-display.scm' | grep -v ';;; note: source file .*scribbu.scm' | grep -v 'newer than compiled')
if [ ! -z "$t_err" ]; then
    printf '=%.0s' $(seq 1 $cols)
	echo "$t_err"
    printf '=%.0s' $(seq 1 $cols)
	exit 1
fi

output=$(echo $t_std|tr \\n :)
if [ "$output" != "<id3v1-tag Sinead O'Connor - Easter Rebellion (Performed by> <id3v2-tag The Pogues - Lorca's Novena (335921 bytes padding)>:" ]; then
    echo $output
    exit 1
fi

