#!/usr/bin/env bash
# Cf. https://stackoverflow.com/questions/11027679/store-capture-stdout-and-stderr-in-different-variables-bash
eval "$(../src/scribbu -L ${srcdir}/../scheme -s ${srcdir}/test-cleanup-encoded-by.scm ${srcdir} \
        2> >(t_err=$(cat); typeset -p t_err) \
         > >(t_std=$(cat); typeset -p t_std) )"
t_stat=$?
echo "stdout: $t_std"
if [ ! -z "$t_err" ]; then
	echo "stderr: $t_err"
	exit 1
fi

../src/scribbu dump elliot-goldenthal.id3v1.tag.out > test-cleanup-encoded-by.out || exit 1
diff test-cleanup-encoded-by.out ${srcdir}/data/golden-test-cleanup-encoded-by.out || exit 1

exit $t_stat
