#!/usr/bin/env bash
macmd5sum() {
    local ckg
    local ckt
    local fl
    while IFS='' read -r line || [[ -n "$line" ]]; do
        ckg=$(echo "$line"|awk '{print $1}')
        fl=$(echo "$line"|awk '{print $2}')
        ckt=$(md5 -q $fl)
        if [ "$ckg" != "$ckt" ]; then
            echo "$fl: $cgk != $ckt"
            exit 1
        fi
    done < "$2"
}

case $(uname) in
    Darwin)
        MD5=macmd5sum;;
    *)
        MD5=md5sum;;
esac

../src/scribbu split --suffix=A ${srcdir}/data/lorca.mp3
$MD5 -c ${srcdir}/data/splitA.md5 || exit 1
../src/scribbu split --suffix=B ${srcdir}/data/红颜旧.mp3
$MD5 -c ${srcdir}/data/splitB.md5 || exit 1

exit 0
