#!/usr/bin/env bash
SCRIPT_FILE=/tmp/test-with-track-in.$$
OUTPUT_FILE=/tmp/test-with-track-in.out.$$
cat <<EOF > $SCRIPT_FILE
(use-modules (ice-9 format))
(use-modules (scribbu))

(setlocale LC_ALL "")

(scribbu/with-track-in 
 "${srcdir}/data"
 (lambda (x) 
   (if (scribbu/has-id3v1-tag x) 
	   (let ((c (scribbu/get-id3v1-string x 'comment))
			 (r (make-regexp "rip.*winamp" regexp/icase)))
		 (if (regexp-exec r c)
			 (format #t "~s: ~s\n" (scribbu/get-path x) c))))))
EOF
../src/scribbu -f $SCRIPT_FILE > $OUTPUT_FILE
# This is irritating, but we need to strip out the paths above
# "data" since we do a dumb diff, below.
sed -e 's_^".*/data_"data_' $OUTPUT_FILE | sort > with-track-in.log
diff with-track-in.log ${srcdir}/data/with-track-in-golden.log || exit 1
exit 0
