# Docker image for building, debugging & packaging -*- mode: dockerfile -*-
FROM debian:stable-slim AS base

ARG DEBIAN_FRONTEND
ENV DEBIAN_FRONTEND=${DEBIAN_FRONTEND:-noninteractive}
# The test suite won't work if this isn't set.
ENV LANG="C.UTF-8"

# Needed for packaging
ENV DEBFULLNAME="Michael Herstine"
ENV DEBEMAIL="sp1ff@pobox.com"

# Install packages
RUN set -ex && \
	apt-get update && \
	apt-get install -y --no-install-recommends \
	flex bison libboost-all-dev libssl-dev zlib1g-dev libunistring-dev libffi-dev guile-2.2-dev \
	less procps gdb \
	debhelper build-essential dh-make devscripts && \
	apt-get clean && \
	rm -rf /tmp/* /var/tmp/* && \
	ln -fs /usr/share/zoneinfo/US/Pacific /etc/localtime && dpkg-reconfigure -f noninteractive tzdata
