.\" Copyright (C) 2021-2024 Michael Herstine <sp1ff@pobox.com>
.\" You may distribute this file under the terms of the GNU Free
.\" Documentation License.
.TH scribbu-encodings 1 2024-10-09 "scribbu 0.7.1" "scribbu Manual"
.SH NAME
scribbu encodings \- List the character encodings supported by scribbu
.SH SYNOPSIS
.BR "scribbu encodings " "[-h] [--help] [--info]"

.SH DESCRIPTION

Several scribbu sub-commands take character encodings as arguments. It is not
always clear how to name them textually. This sub-command will print the
list of supported encodings along with their textual representations.

.SH ENCODINGS

.IP \(bu 2
ASCII
.IP \(bu 2
ISO-8859-1
.IP \(bu 2
ISO-8859-2
.IP \(bu 2
ISO-8859-3
.IP \(bu 2
ISO-8859-4
.IP \(bu 2
ISO-8859-5
.IP \(bu 2
ISO-8859-7
.IP \(bu 2
ISO-8859-9
.IP \(bu 2
ISO-8859-10
.IP \(bu 2
ISO-8859-13
.IP \(bu 2
ISO-8859-14
.IP \(bu 2
ISO-8859-15
.IP \(bu 2
ISO-8859-16
.IP \(bu 2
KOI8-R
.IP \(bu 2
KOI8-U
.IP \(bu 2
KOI8-RU
.IP \(bu 2
CP1250
.IP \(bu 2
CP1251
.IP \(bu 2
CP1252
.IP \(bu 2
CP1253
.IP \(bu 2
CP1254
.IP \(bu 2
CP1257
.IP \(bu 2
CP850
.IP \(bu 2
CP866
.IP \(bu 2
CP1131
.IP \(bu 2
MacRoman
.IP \(bu 2
MacCentralEurope
.IP \(bu 2
MacIceland
.IP \(bu 2
MacCroatian
.IP \(bu 2
MacRomania
.IP \(bu 2
MacCyrillic
.IP \(bu 2
MacUkraine
.IP \(bu 2
MacGreek
.IP \(bu 2
MacTurkish
.IP \(bu 2
Macintosh
.IP \(bu 2
ISO-8859-6
.IP \(bu 2
ISO-8859-8
.IP \(bu 2
CP1255
.IP \(bu 2
CP1256
.IP \(bu 2
CP862
.IP \(bu 2
MacHebrew
.IP \(bu 2
MacArabic
.IP \(bu 2
EUC-JP
.IP \(bu 2
SHIFT-JIS
.IP \(bu 2
CP932
.IP \(bu 2
ISO-2022-JP
.IP \(bu 2
ISO-2022-JP-2
.IP \(bu 2
ISO-2022-JP-1
.IP \(bu 2
ISO-2022-JP-MS
.IP \(bu 2
EUC-CN
.IP \(bu 2
HZ
.IP \(bu 2
GBK
.IP \(bu 2
CP936
.IP \(bu 2
GB18030
.IP \(bu 2
EUC-TW
.IP \(bu 2
BIG5
.IP \(bu 2
CP950
.IP \(bu 2
BIG5-HKSCS
.IP \(bu 2
BIG5-HKSCS:2004
.IP \(bu 2
BIG5-HKSCS:2001
.IP \(bu 2
BIG5-HKSCS:1999
.IP \(bu 2
ISO-2022-CN
.IP \(bu 2
ISO-2022-CN-EXT
.IP \(bu 2
EUC-KR
.IP \(bu 2
CP949
.IP \(bu 2
ISO-2022-KR
.IP \(bu 2
JOHAB
.IP \(bu 2
ARMSCII-8
.IP \(bu 2
Georgian-Academy
.IP \(bu 2
Georgian-PS
.IP \(bu 2
KOI8-T
.IP \(bu 2
PT154
.IP \(bu 2
RK1048
.IP \(bu 2
TIS-620
.IP \(bu 2
CP874
.IP \(bu 2
MacThai
.IP \(bu 2
MuleLao-1
.IP \(bu 2
CP1133
.IP \(bu 2
VISCII
.IP \(bu 2
TCVN
.IP \(bu 2
CP1258
.IP \(bu 2
HP-ROMAN8
.IP \(bu 2
NEXTSTEP
.IP \(bu 2
UTF-8
.IP \(bu 2
UCS-2
.IP \(bu 2
UCS-2BE
.IP \(bu 2
UCS-2LE
.IP \(bu 2
UCS-4
.IP \(bu 2
UCS-4BE
.IP \(bu 2
UCS-4LE
.IP \(bu 2
UTF-16
.IP \(bu 2
UTF-16BE
.IP \(bu 2
UTF-16LE
.IP \(bu 2
UTF-32
.IP \(bu 2
UTF-32BE
.IP \(bu 2
UTF-32LE
.IP \(bu 2
UTF-7
.IP \(bu 2
C99
.IP \(bu 2
JAVA

.SH AUTHOR

.B scribbu
is written & maintained by Michael Herstine <sp1ff@pobox.com>. It
is maintained at https://github.com/sp1ff/scribbu.

.SH "SEE ALSO"

.BR  scribbu "(1), " scribbu-dump "(1), " scribbu-genre "(1), " scribbu-popm "(1), " scribbu-rename "(1), " scribbu-report "(1), " scribbu-split "(1), " scribbu-text "(1), " scribbu-m3u "(1)"
