#!/bin/bash

# This script is meant to be run inside a docker container (presumably
# scribbu-arch:latest). It assumes there is an Autotools tarball in /, and that
# it can find the PKGBUILD file in /arch.
set -ex
base="$(basename $1 .tar.gz)"
version="${base:8}"
cp -v "$1" /tmp
cp -v /scribbu-arch/PKGBUILD-dev /tmp/PKGBUILD
cd tmp
makepkg -g >> PKGBUILD
makepkg
cp -v scribbu-${version}-1-x86_64.pkg.tar.zst /scribbu-arch
