#!/usr/bin/env bash

# This script will build the scribbu Debian package in a Docker container.

# It is assumed to be run from the scribbu-deb directory.

set -ex
scribbu_dev=$(cd ../scribbu && pwd)
admin=${scribbu_dev}/admin
docker build -t scribbu-arch:latest -f ${admin}/Dockerfile-arch .

docker_args="-it"
docker_args="$docker_args --mount type=bind,source=$(pwd),target=/scribbu-arch"
# docker_args="$docker_args -v ${script}:/build-dev-pkg:ro"
docker_args="$docker_args --privileged"
docker_args="$docker_args -u mgh"

# Un-comment to just drop into the container
cmd="docker run ${docker_args} scribbu-arch:latest"
# cmd="docker run ${docker_args} scribbu-arch:latest /build-pkg-cnt $1"
exec $cmd
