# Docker image for building, debugging & packaging     -*- mode: dockerfile -*-
FROM debian:stable-slim AS base

ARG DEBIAN_FRONTEND
ENV DEBIAN_FRONTEND=${DEBIAN_FRONTEND:-noninteractive}

# The test suite won't work if this isn't set:
ENV LANG="C.UTF-8"
# Needed for Debian packaging:
ENV DEBFULLNAME="Michael Herstine"
ENV DEBEMAIL="sp1ff@pobox.com"

RUN set -ex && \
	apt-get update && \
	apt-get install -y --no-install-recommends \
        # scribbu pre-requisites \
	flex bison libboost-all-dev libssl-dev zlib1g-dev libunistring-dev libffi-dev guile-2.2-dev texinfo \
        # for packaging \
	debhelper build-essential dh-make devscripts git-buildpackage lintian \
        # for my sanity \
	less procps gdb sudo && \
        # tidy-up \
	apt-get clean && \
	rm -rf /tmp/* /var/tmp/* && \
        # set the timezone to civilization (i.e. the Pacific) \
	ln -fs /usr/share/zoneinfo/US/Pacific /etc/localtime && dpkg-reconfigure -f noninteractive tzdata
