# Test workflow for experimentiong with the locale
name: test-locale
on:
  workflow_dispatch:

env:
  LANG: "en_US.UTF-8"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: test
      run: |
        sudo locale-gen en_US.UTF-8
        sudo update-locale LANG=en_US.UTF-8
    - name: check
      run: |
        echo "$LANG"
        locale
